version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "wxx9248"
    commit-message:
      prefix: "Dependency Updates"
    reviewers:
      - "wxx9248"
