name: pull-request-build
on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      - name: Setup pnpm
        run: |
          npm install --global pnpm
      - name: Fetching node modules
        run: |
          pnpm install
      - name: Build distributable
        run: |
          pnpm build-only
